name: Trigger Consumer Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trigger-consumer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Trigger Consumer Workflow
      env:
        GITHUB_TOKEN: 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
      run: |
        curl -X POST \
        -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.everest-preview+json" \
        https://api.github.com/repos/duttabhishek0/Consumer/dispatches \
        -d '{"event_type": "trigger-consumer-workflow"}'
