name: Producer Stub Generation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-stubs:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    env:
      # Application properties
      SPRING_APPLICATION_NAME: productservice
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/test_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_MAIN_WEB_APPLICATION_TYPE: none
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate Stubs
        run: mvn clean install

      - name: Upload Stubs to Another Repo
        env:
          REPO_URL: https://github.com/duttabhishek0/temp-stubs.git
          BRANCH_NAME: master
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          mkdir -p stubs
          cp -r target/stubs/* temp-stubs/  # Adjust path if using Gradle
          cd temp-stubs
          git init
          git config --global user.email "duttabhishek0@gmail.com"
          git config --global user.name "Abhishek Dutt"
          git remote add origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/duttabhishek0/temp-stubs.git
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "Upload stubs"
          git push -u origin $BRANCH_NAME --force

      - name: Trigger Consumer Workflow
        env:
          GITHUB_TOKEN: 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
        run: |
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/repos/duttabhishek0/Consumer/dispatches \
          -d '{"event_type": "trigger-consumer-workflow"}'